"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useParams } from "next/navigation";
import { EvidenceLightbox, EvidenceThumb, useEvidenceViewer } from "@/components/EvidenceViewer";
import { MAX_BYTES, MAX_EVIDENCE_PER_ASSIGNMENT, kindOfMime, type EvidenceKind } from "@/core/upload-policy";

type CaptureMode = EvidenceKind;
type SignedUpload = { url: string; key: string; headers?: Record<string, string> };
type MyAssignment = { assignmentId: string };
type ExistingEvidence = { id: string; kind: EvidenceKind; mime: string; url: string };

const modes: { kind: CaptureMode; label: string; accept: string }[] = [
  { kind: "image", label: "照片", accept: "image/jpeg,image/png,image/webp" },
  { kind: "audio", label: "录音", accept: "audio/mp4,audio/mpeg,audio/webm" },
  { kind: "video", label: "录像", accept: "video/mp4,video/webm" },
];

function recorderMime(kind: CaptureMode): string { return kind === "audio" ? "audio/webm" : "video/webm"; }
function isSecureCaptureContext(): boolean { return window.isSecureContext || ["localhost", "127.0.0.1", "[::1]"].includes(window.location.hostname); }

export default function UploadEvidencePage() {
  const { id } = useParams<{ id: string }>();
  const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null); const recorderRef = useRef<MediaRecorder | null>(null); const chunksRef = useRef<Blob[]>([]); const assignmentIdRef = useRef<string | null>(null); const fileInputRef = useRef<HTMLInputElement>(null);
  const [mode, setMode] = useState<CaptureMode>("image"); const [fallback, setFallback] = useState(false); const [recording, setRecording] = useState(false); const [progress, setProgress] = useState(0); const [message, setMessage] = useState(""); const [done, setDone] = useState(false); const [evidence, setEvidence] = useState<ExistingEvidence[]>([]); const viewer = useEvidenceViewer();
  const stopStream = useCallback(() => { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; }, []);
  const startCamera = useCallback(async (nextMode: CaptureMode) => {
    stopStream(); if (!isSecureCaptureContext() || !navigator.mediaDevices?.getUserMedia) { setFallback(true); return; }
    try { const stream = await navigator.mediaDevices.getUserMedia(nextMode === "audio" ? { audio: true } : { video: { facingMode: "environment" }, audio: nextMode === "video" }); streamRef.current = stream; if (videoRef.current && nextMode !== "audio") { videoRef.current.srcObject = stream; await videoRef.current.play().catch(() => undefined); } setFallback(false); } catch { setFallback(true); }
  }, [stopStream]);
  useEffect(() => { fetch(`/api/activities/${id}/my-assignment`).then((response) => response.ok ? response.json() : null).then((assignment: MyAssignment | null) => { assignmentIdRef.current = assignment?.assignmentId ?? null; if (assignment?.assignmentId) fetch(`/api/assignments/${assignment.assignmentId}/evidence`).then((response) => response.ok ? response.json() : null).then((data: { evidence: ExistingEvidence[] } | null) => setEvidence(data?.evidence ?? [])).catch(() => undefined); }).catch(() => undefined); }, [id]);
  useEffect(() => { void startCamera(mode); return stopStream; }, [mode, startCamera, stopStream]);
  useEffect(() => () => { if (recorderRef.current?.state === "recording") recorderRef.current.stop(); }, []);
  const upload = useCallback(async (file: File) => {
    const kind = kindOfMime(file.type); if (kind === null) { setMessage("这个格式不收"); return; } if (file.size > MAX_BYTES[kind]) { setMessage("文件太大了，请压缩体积"); return; } if (!assignmentIdRef.current) { setMessage("任务还没接上，退回再进一次"); return; }
    try { setMessage(""); setProgress(0.35); const signedResponse = await fetch(`/api/assignments/${assignmentIdRef.current}/evidence/sign`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mime: file.type, bytes: file.size }) }); if (!signedResponse.ok) throw new Error("sign"); const signed = await signedResponse.json() as SignedUpload; setProgress(0.7); const directUrl = new URL(signed.url, window.location.origin); const directResponse = await fetch(directUrl, { method: "PUT", headers: signed.headers, body: file }); if (!directResponse.ok) throw new Error("direct"); setProgress(0.9); const confirmResponse = await fetch(`/api/assignments/${assignmentIdRef.current}/evidence`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ key: signed.key, kind, mime: file.type, bytes: file.size }) }); if (!confirmResponse.ok) throw new Error("confirm"); setProgress(1); setDone(true); stopStream(); const listed = await fetch(`/api/assignments/${assignmentIdRef.current}/evidence`); if (listed.ok) { const data = await listed.json() as { evidence: ExistingEvidence[] }; setEvidence(data.evidence); } } catch { setProgress(0); setMessage("上传没接上，换一个再试"); }
  }, [stopStream]);
  function takePhoto() { const video = videoRef.current; if (!video || video.videoWidth === 0) { setMessage("镜头还没就位"); return; } const canvas = document.createElement("canvas"); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext("2d")?.drawImage(video, 0, 0); canvas.toBlob((blob) => { if (blob) void upload(new File([blob], "evidence.jpg", { type: "image/jpeg" })); }, "image/jpeg"); }
  function toggleRecording() { if (recording) { recorderRef.current?.stop(); return; } if (!streamRef.current || typeof MediaRecorder === "undefined") { setFallback(true); return; } try { const mimeType = recorderMime(mode); const recorder = MediaRecorder.isTypeSupported(mimeType) ? new MediaRecorder(streamRef.current, { mimeType }) : new MediaRecorder(streamRef.current); chunksRef.current = []; recorder.ondataavailable = (event) => { if (event.data.size > 0) chunksRef.current.push(event.data); }; recorder.onstop = () => { setRecording(false); const type = recorder.mimeType || mimeType; void upload(new File([new Blob(chunksRef.current, { type })], "evidence.webm", { type })); }; recorderRef.current = recorder; recorder.start(); setRecording(true); } catch { setFallback(true); } }
  const current = modes.find((item) => item.kind === mode)!;
  return <main className="mx-auto flex min-h-[100dvh] max-w-[420px] flex-col bg-ground text-body"><div className="fixed left-0 top-0 z-10 h-0.5 bg-mark transition-[width] duration-200" style={{ width: `${progress * 100}%` }} aria-hidden="true" /><section className="relative flex min-h-[58dvh] flex-1 items-center justify-center overflow-hidden bg-redact">{fallback ? <label className="flex min-h-48 w-full cursor-pointer flex-col items-center justify-center gap-3 px-8 text-center text-dim">这儿唤不起相机<span className="text-[12px]">从手机里挑一份传上来</span><span className="rounded-full border border-line px-4 py-2 text-bright">从手机上传</span><input ref={fileInputRef} className="sr-only" type="file" aria-label="上传证据文件" accept={current.accept} onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) void upload(file); event.currentTarget.value = ""; }} /></label> : mode === "audio" ? <p className="text-sm text-dim">录下这一刻</p> : <video ref={videoRef} className="h-full w-full object-cover" muted playsInline aria-label="相机取景器" />}{done ? <span className="absolute text-2xl text-mark" aria-label="已上传">✓</span> : null}</section><section className="px-5 pb-[max(2rem,env(safe-area-inset-bottom))] pt-5"><a href={`/a/${id}`} className="text-[13px] text-dim">&lt; 回这一局</a><div className="h-4" />{message ? <p role="alert" className="mb-4 text-sm text-mark">{message}</p> : null}<p className="mb-3 text-sm text-dim">已传 {evidence.length} 份，还能传 {Math.max(0, MAX_EVIDENCE_PER_ASSIGNMENT - evidence.length)} 份</p>{evidence.length ? <div className="mb-5 flex gap-2 overflow-x-auto">{evidence.map((item, index) => <EvidenceThumb key={item.id} item={item} label={`第 ${index + 1} 份证据`} onOpen={viewer.open} />)}</div> : null}<div className="mb-5 grid grid-cols-3 rounded-full border border-line p-1">{modes.map((item) => <button key={item.kind} type="button" className={`min-h-10 rounded-full text-sm font-bold ${mode === item.kind ? "bg-raised text-mark" : "text-dim"}`} onClick={() => { setMessage(""); setDone(false); setMode(item.kind); }}>{item.label}</button>)}</div><button type="button" className="min-h-14 w-full rounded-full bg-mark px-5 font-bold text-ground disabled:opacity-60" disabled={evidence.length >= MAX_EVIDENCE_PER_ASSIGNMENT} onClick={fallback ? () => fileInputRef.current?.click() : mode === "image" ? takePhoto : toggleRecording}>{fallback ? "从手机上传" : mode === "image" ? "拍下" : recording ? "停下" : mode === "audio" ? "开始录音" : "开始录像"}</button></section><EvidenceLightbox item={viewer.zoomed} onClose={viewer.close} /></main>;
}
