"use client";

import { FormEvent, useState } from "react";
import { useParams } from "next/navigation";

type Review = { verdict: "accept" | "revise" | "reject"; canForceSubmit: boolean; scores: { feasibility: number; stealth: number; fun: number; verifiability: number; safety: "ok" | "warn" | "block"; suggestions: string[] } };
const scoreLabels = { feasibility: "可完成", stealth: "隐蔽", fun: "好玩", verifiability: "可留证" } as const;

export default function TaskPage() {
  const { id } = useParams<{ id: string }>(); const [content, setContent] = useState(""); const [review, setReview] = useState<Review | null>(null); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const response = await fetch(`/api/activities/${id}/tasks`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ content }) }); if (!response.ok) return setError("这题没送进去。"); setReview(await response.json() as Review); }
  const blocked = review?.verdict === "reject";
  return <main className="mx-auto flex min-h-[100dvh] max-w-[420px] flex-col px-5 py-8"><p className="text-[12px] tracking-[.3em] text-mark">写一道题</p><h1 className="mt-3 text-3xl font-bold text-bright">让人做得到，<br />又不容易被猜到。</h1><form onSubmit={submit} className="mt-8 flex flex-1 flex-col"><textarea value={content} onChange={(e) => { setContent(e.target.value); setReview(null); }} maxLength={500} placeholder="比如：想办法让左边的人主动说出一个动物名" className="min-h-40 w-full rounded-xl border border-line bg-surface p-4 leading-7 text-bright outline-none focus:border-mark" />{review ? <section className="mt-5 rounded-2xl border border-line bg-surface p-4"><p className={blocked ? "font-bold text-alarm" : "font-bold text-mark"}>{blocked ? "这题不行" : review.verdict === "revise" ? "能玩，但该改改" : "这题能上"}</p><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(scoreLabels).map(([key, label]) => <div key={key} className="rounded-xl bg-raised p-3"><p className="text-[12px] text-dim">{label}</p><p className="mt-1 text-xl font-bold tabular-nums text-bright">{review.scores[key as keyof typeof scoreLabels]}</p></div>)}</div>{review.verdict === "revise" ? <p className="mt-4 text-[14px] leading-6 text-body">{review.scores.suggestions[0] ?? "把范围再收一点，别让人一眼就锁定答案。"}</p> : null}{blocked ? <p className="mt-4 text-[14px] text-body">换个题。这里不给绕过。</p> : null}</section> : null}<div className="mt-auto pt-6"><button disabled={!content.trim() || blocked} className="min-h-14 w-full rounded-full bg-mark text-[16px] font-bold text-ground disabled:cursor-not-allowed disabled:bg-raised disabled:text-dim">{review?.verdict === "revise" && review.canForceSubmit ? "就按这题提交" : "提交并预审"}</button>{error ? <p role="alert" className="mt-3 text-[13px] text-alarm">{error}</p> : null}</div></form></main>;
}
